=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/userCenter/userCenter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
	<xs:include schemaLocation=""></xs:include>
	<xs:element name="meiQiReferrer">           
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sections" maxOccurs="unbounded"
                    minOccurs="0" type="Section" />
                <xs:element name="tools" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- 结构模板 -->

    <xs:complexType name="Section">
                <xs:sequence>
                    <xs:element name="sectionName" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration
                                    value="DesignerInfoSection">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="NormalSection">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="ResidentForNOSection">
                                </xs:enumeration>
                                 <xs:enumeration
                                    value="ResidentForYESSection">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="CommissionSection">
                                </xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="sectionItems" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
                </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SectionItem">
                <xs:sequence>               
                    <xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
                    <xs:element name="viewName" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                            <xs:enumeration
                                    value="NormalCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="ResidentForYESCell">
                                </xs:enumeration>
                                 <xs:enumeration
                                    value="ResidentForNOCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="DesignerInfoCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="CommissionCell">
                                </xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
                    <xs:element name="actions" type="Action" maxOccurs="unbounded" minOccurs="0"></xs:element>
                </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Action">
    <xs:sequence>
    <xs:element name="actionName" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string"> 
    					<xs:enumeration value="myOrderCommand"></xs:enumeration>
    					<xs:enumeration value="myCollectionCommand"></xs:enumeration>
    					<xs:enumeration value="aboutUsCommand"></xs:enumeration> 
    					<xs:enumeration value="processStatusCommand"></xs:enumeration>
    					<xs:enumeration value="succeedStatusCommand"></xs:enumeration>
    					<xs:enumeration value="failedStatusCommand"></xs:enumeration>
    					<xs:enumeration value="designerInfoCommand"></xs:enumeration>
    					<xs:enumeration value="checkoutKnowsCommand"></xs:enumeration>
    					<xs:enumeration value="commissionDetailsCommand"></xs:enumeration>
    					<xs:enumeration value="settingsCommand"></xs:enumeration>
    					<xs:enumeration value="orderQueryCommand"></xs:enumeration>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="sender" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="NormalCell"></xs:enumeration>
    					<xs:enumeration value="ResidentForYESCell"></xs:enumeration>
    					<xs:enumeration value="ResidentForNOCell"></xs:enumeration> 
    					<xs:enumeration value="DesignerInfoCell"></xs:enumeration>
    					<xs:enumeration value="CommissionCell"></xs:enumeration> 
    					<xs:enumeration value="btnCheckoutKnows"></xs:enumeration> 
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="title" type="xs:string" minOccurs="0"/>
    		<xs:element name="actionValue"  minOccurs="0"/> 
    	</xs:sequence>
    </xs:complexType>
    
    <!--数据实体类-->		
    <xs:complexType name='ApplyEntryLog'>
		<xs:sequence>			
			<xs:element name="url" type="stringtype" /> <!--入驻状态url-->
			<xs:element name="applyStatus " type="stringtype" />
			<xs:element name="applyLog " type="stringtype" />
	</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name='Commission'>
		<xs:sequence>			
			<xs:element name="setteDate" type="stringtype" /> <!-- 最新入账时间-->
			<xs:element name="historySettle" type="inttype" /> <!-- 历史收益-->	
			<xs:element name="notSettlePrice" type="inttype" /> <!-- 未结算佣金-->	
			<xs:element name="newSettle" type="inttype" /> <!-- 最新入账-->	
		</xs:sequence>
	</xs:complexType>  
	<xs:complexType name='Designer'>
		<xs:sequence>		
			<xs:element name="designerImgv" type="stringtype" /> <!-- 设计师头像-->	
			<xs:element name="designerName" type="stringtype" /> <!-- 设计师名字-->	
			<xs:element name="designerCompany" type="stringtype" /> <!-- 设计师公司-->				
		</xs:sequence>
	</xs:complexType>
	<!--常量--> 
	<xs:simpleType name="stringtype">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="inttype">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
    
    
    <xs:complexType name="NormalCell">
    	<xs:sequence>
    		<xs:element name="lblTitle" type="xs:string"></xs:element>
    		<xs:element name="imgLogo" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType> 
    <xs:complexType name="ResidentForNOCell">
    	<xs:sequence>
    		<xs:element name="lblStatus" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    <xs:complexType name="ResidentForYESCell">
    	<xs:sequence>
    		<xs:element name="lblStatus" type="xs:string"></xs:element>
    		<xs:element name="lblDescribe" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    <xs:complexType name="DesignerInfoCell">
    	<xs:sequence>
    	    <xs:element name="lbldesignerImgvLabel" type="xs:string"></xs:element>
    		<xs:element name="lbldesignerNameLabel" type="xs:string"></xs:element>
    		<xs:element name="lbldesignerCompanyLabel" type="xs:string"></xs:element>
    		<xs:element name="imgIdentification" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>  
    <xs:complexType name="CommissionCell">  
    	<xs:sequence>
    		<xs:element name="lblTime" type="xs:string"></xs:element>
    		<xs:element name="lblHistoryIncome" type="xs:string"></xs:element>
    		<xs:element name="lblNotCheckoutPrice" type="xs:string"></xs:element>
    		<xs:element name="lblNewIncome" type="xs:string"></xs:element>
    		<xs:element name="btnCheckoutKnows" type="xs:string"></xs:element>
    	</xs:sequence>
    	</xs:complexType>
</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/userCenter/userCenter_designer_homePage_ipad.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userCenter.xsd">
  <sections>
		<sectionName>DesignerInfoSection</sectionName>
		<sectionItems>
			<viewName>DesignerInfoCell</viewName>
			<data>
			    <lbldesignerImgvLabel>${DesignerInfo.imagv}</lbldesignerImgvLabel>
				<lbldesignerNameLabel>${DesignerInfo.name}</lbldesignerNameLabel>
				<lbldesignerCompanyLabel>${DesignerInfo.company}</lbldesignerCompanyLabel>
				<imgIdentification>已认证图标</imgIdentification>
			</data>
		<actions>
				<actionName>designerInfoCommand</actionName>
				<sender>DesignerInfoCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
	   <sectionItems>
			<viewName>CommissionCell</viewName>
			<data>
			    <lblTime>${DesignerInfo.commission.newIncomeTime}</lblTime>
			    <lblHistoryIncome>${DesignerInfo.commission.historyIncome}</lblHistoryIncome>
			    <lblNotCheckoutPrice>${DesignerInfo.commission.notCheckoutPrice}</lblNotCheckoutPrice>
			    <lblNewIncome>${DesignerInfo.commission.newIncome}</lblNewIncome>
			    <btnCheckoutKnows>结算须知</btnCheckoutKnows>
			</data>
			<actions>
				<actionName>checkoutKnowsCommand</actionName>
				<sender>btnCheckoutKnows</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
  </sections>
  <sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>佣金明细</lblTitle>
				<imgLogo>收益图标</imgLogo>
			</data>
		<actions>
				<actionName>commissionDetailsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
			</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我收藏的商品</lblTitle>
				<imgLogo>收藏图标</imgLogo>
			</data>
			<actions>
				<actionName>myCollectionCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>设置</lblTitle>
				<imgLogo>设置图标</imgLogo>
			</data>
		<actions>
				<actionName>settingsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
			</sectionItems>
		<sectionItems/>
	</sections>	
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>关于乐家购</lblTitle>
				<imgLogo>关于图标</imgLogo>
			</data>
		<actions>
				<actionName>aboutUsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/userCenter/userCenter_applyFailed_ipad.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userCenter.xsd">
  <sections>
		<sectionName>ResidentForNOSection</sectionName>
		<sectionItems>
			<viewName>ResidentForNOCell</viewName>
			<data>
				<lblStatus>抱歉，您的入驻申请未通过审核！</lblStatus>
			</data>
		<actions>
				<actionName>processStatusCommand</actionName>
				<sender>ResidentForNOCell</sender>
				<actionValue>${ApplyEntryLog.url}</actionValue>
			</actions>
			<actions/>
			</sectionItems>
			<sectionItems/>
	</sections>
  <sections>
	<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我的订单</lblTitle>
				<imgLogo>订单图标1</imgLogo>
			</data>
		<actions>
				<actionName>myOrderCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue>YES</actionValue>
			</actions>
			<actions/>
			</sectionItems>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>订单查询</lblTitle>
				<imgLogo>订单查询图标</imgLogo>
			</data>
			<actions>
				<actionName>orderQueryCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
  </sections>
  <sections>
       <sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我收藏的商品</lblTitle>
				<imgLogo>收藏图标</imgLogo>
			</data>
			<actions>
				<actionName>myCollectionCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
  </sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>关于乐家购</lblTitle>
				<imgLogo>关于图标</imgLogo>
			</data>
		<actions>
				<actionName>aboutUsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/userCenter/userCenter_applyProcess_android.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userCenter.xsd">
  <sections>
		<sectionName>ResidentForNOSection</sectionName>
		<sectionItems>
			<viewName>ResidentForNOCell</viewName>
			<data>
				<lblStatus>您的入驻申请正在审核中</lblStatus>
			</data>
		<actions>
				<actionName>processStatusCommand</actionName>
				<sender>ResidentForNOCell</sender>
				<actionValue>${ApplyEntryLog.url}</actionValue>
			</actions>
			<actions/>
			</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我的订单</lblTitle>
				<imgLogo>ic40</imgLogo>
			</data>
		<actions>
				<actionName>myOrderCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>订单查询</lblTitle>
				<imgLogo>ic41</imgLogo>
			</data>
			<actions>
				<actionName>orderQueryCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
	</sections>
	<sections>
	   <sectionName>NormalSection</sectionName>
	   <sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我收藏的商品</lblTitle>
				<imgLogo>ic24</imgLogo>
			</data>
			<actions>
				<actionName>myCollectionCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>关于乐家购</lblTitle>
				<imgLogo>ic39</imgLogo>
			</data>
		<actions>
				<actionName>aboutUsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/userCenter/userCenter_applySucceed_android.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userCenter.xsd">
  <sections>
		<sectionName>ResidentForYESSection</sectionName>
		<sectionItems>
			<viewName>ResidentForYESCell</viewName>
			<data>
				<lblStatus>您已成功入驻乐家购！</lblStatus>
				<lblDescribe>点击立即登录</lblDescribe>
			</data>
		<actions>
				<actionName>succeedStatusCommand</actionName>
				<sender>ResidentForYESCell</sender>
				<actionValue>${ApplyEntryLog.url}</actionValue>
			</actions>
			<actions/>
			</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我的订单</lblTitle>
				<imgLogo>ic40</imgLogo>
			</data>
		<actions>
				<actionName>myOrderCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
	    <sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>订单查询</lblTitle>
				<imgLogo>ic41</imgLogo>
			</data>
			<actions>
				<actionName>orderQueryCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
	</sections>
	<sections>
	    <sectionName>NormalSection</sectionName>
	    <sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>我收藏的商品</lblTitle>
				<imgLogo>ic24</imgLogo>
			</data>
			<actions>
				<actionName>myCollectionCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>	
	<sections>
		<sectionName>NormalSection</sectionName>
		<sectionItems>
			<viewName>NormalCell</viewName>
			<data>
				<lblTitle>关于乐家购</lblTitle>
				<imgLogo>ic39</imgLogo>
			</data>
		<actions>
				<actionName>aboutUsCommand</actionName>
				<sender>NormalCell</sender>
				<actionValue></actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
</meiQiReferrer>
