=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/commissionDetails/commissionDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
	<xs:include schemaLocation=""></xs:include>
    <xs:element name="meiQiReferrer">    		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sections" type="Section" maxOccurs="unbounded" minOccurs="1"></xs:element>
				<xs:element name="tools" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
			</xs:sequence>
		</xs:complexType>
    </xs:element>

<!-- 结构模板 -->

  <xs:complexType name="Section">
    			<xs:sequence>
    				<xs:element name="sectionName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="CommissionListDetailsSection">
    							</xs:enumeration>
    							</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="sectionItems" type="SectionItem"
    					maxOccurs="unbounded" minOccurs="0">
    				</xs:element>
    			</xs:sequence>
    </xs:complexType>

	<xs:complexType name="SectionItem">
    			<xs:sequence>    			
    				<xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
    				<xs:element name="viewName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration value="CommissionListDetailsTitleCell"></xs:enumeration>
    							<xs:enumeration value="CommissionListDetailsOrderCell"></xs:enumeration>
    							<xs:enumeration value="CommissionListDetailsDealCell"></xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
    				<xs:element name="actions" type="Action" maxOccurs="unbounded" minOccurs="0"></xs:element>
    			</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Action">
    	<xs:sequence>
    		<xs:element name="actionName" minOccurs="0"> 		
				<xs:simpleType> 
					<xs:restriction base="xs:string">			
					<xs:enumeration value="OrderCommand"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
    		<xs:element name="sender" minOccurs="0"> 
    		    <xs:simpleType>
    		        <xs:restriction base="xs:string">			
					<xs:enumeration value="CommissionDetailsOrderCell"></xs:enumeration>
					</xs:restriction>
    		    </xs:simpleType>
    		    </xs:element>
    		<xs:element name="title" minOccurs="0"></xs:element>
    		<xs:element name="actionValue" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

<!-- 数据结构 -->

    <xs:complexType name="CommissionListDetailsTitleCell">
    	<xs:sequence>
    		<xs:element name="lblPrice" type="xs:string"></xs:element>
    		<xs:element name="lblSettled" type="xs:string"></xs:element>
    		<xs:element name="lblSettling" type="xs:string"></xs:element>
    		</xs:sequence>
    </xs:complexType>
 

    <xs:complexType name="CommissionListDetailsOrderCell">
    	<xs:sequence>
    		<xs:element name="lblOderNumber" type="xs:string"></xs:element>
    		<xs:element name="lblOderPrice" type="xs:string"></xs:element>
    		<xs:element name="lblOderDate" type="xs:string"></xs:element>
    		</xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="CommissionListDetailsDealCell">
    	<xs:sequence>
    		<xs:element name="lblAccount" type="xs:string"></xs:element> 
    		<xs:element name="lblBankName" type="xs:string"></xs:element>
    		<xs:element name="lblDealNumber" type="xs:string"></xs:element>
    		<xs:element name="lblDealDate" type="xs:string"></xs:element>
    		</xs:sequence>
    </xs:complexType>
    
    
    
    
</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/commissionDetails/CommissionDetails_settle_iphone.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommissionDetails.xsd">
	<sections>
		<sectionName>CommissionListDetailsSection</sectionName>
		<sectionItems>
			<viewName>CommissionListDetailsTitleCell</viewName>
			<data>
				<lblPrice>${Commission.price}</lblPrice>
				<lblSettled>已结算</lblSettled>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>CommissionListDetailsOrderCell</viewName>
			<data>
				<lblOrderNumber>${Commission.orderSn}</lblOrderNumber>
				<lblOrderPrice>${Commission.orderAmount}</lblOrderPrice>
				<lblDate>${Commission.createDate}</lblDate>
			</data>
			<actions>
				<actionName>OrderCommand</actionName>
				<sender>CommissionDetailsOrderCell</sender>
				<actionValue>${OrderItem.orderId}</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems>
			<viewName>CommissionListDetailsDealCell</viewName>
			<data>
				<lblAccount>${Commission.account}</lblAccount>
				<lblBankName>${Commission.account.bankName}</lblBankName>
				<lblDealNumber>${Commission.orderSn}</lblDealNumber>
				<lblDealDate>${Commission.date}</lblDealDate>
			</data>
		</sectionItems>
	</sections>
	<sections/>
</meiQiReferrer>
