=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/commissionList/commissionList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
    <xs:element name="meiQiReferrer">    		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sections" type="Section" maxOccurs="unbounded" minOccurs="0"></xs:element>
				<xs:element name="tools" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
			</xs:sequence>
		</xs:complexType>
    </xs:element>

<!-- 结构模板 -->

    <xs:complexType name="Section">
    			<xs:sequence>
    			    <xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
    				<xs:element name="sectionName"  minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="CommissionListSection">
    							</xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="header" type="SectionItem"  minOccurs="0"></xs:element>
    				<xs:element name="sectionItems" type="SectionItem"	maxOccurs="unbounded" minOccurs="0">
    				</xs:element>
    			</xs:sequence>
    </xs:complexType>   

	<xs:complexType name="SectionItem">
    			<xs:sequence>    			
    				<xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
    				<xs:element name="viewName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration value="CommissionListCell"></xs:enumeration>
    							<xs:enumeration value="CommissionHeaderCell"></xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
    				<xs:element name="actions" type="Action" maxOccurs="unbounded" minOccurs="0"></xs:element>
    			</xs:sequence>
    </xs:complexType>   

    
    
    
    <xs:complexType name="Action">
    	<xs:sequence>
    		<xs:element name="actionName" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="clickCommissonCellCommand"></xs:enumeration> 
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="sender" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="btnAll"></xs:enumeration>
    					<xs:enumeration value="btnCompleted"></xs:enumeration>
    					<xs:enumeration value="btnNoCompleted"></xs:enumeration>
    					<xs:enumeration value="CommissonListDetailCell"></xs:enumeration>
    					<xs:enumeration value="CommissionListCell"></xs:enumeration> 
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="title" type="xs:string" minOccurs="0"/>
    		<xs:element name="actionValue"  minOccurs="0"/>
    	</xs:sequence>
    </xs:complexType>

    

<!-- 数据结构 -->

    <xs:complexType name="CommissionHeaderCell">
        <xs:sequence>
            <xs:element name="lblHeader" type="xs:string"></xs:element>
            <xs:element name="lblPrice" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CommissionListCell">
    	<xs:sequence>
    		<xs:element name="lblDate" type="xs:string"></xs:element>
    		<xs:element name="lblPrice" type="xs:string"></xs:element>
    		<xs:element name="lblOrderNumber" type="xs:string"></xs:element>
    		<xs:element name="lblOrderAmount" type="xs:string"></xs:element>  
    		<xs:element name="lblSettleDate" type="xs:string"></xs:element>
    		<xs:element name="lblSettled" type="xs:string"></xs:element>
    		<xs:element name="lblSettling" type="xs:string"></xs:element>    		
    	</xs:sequence>
    </xs:complexType>
    

    
    
    
</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/commissionList/commissionList_ipad.xml
<?xml version="1.0" encoding="UTF-8"?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="commissionList.xsd">
	<sections>
		<sectionName>CommissionListSection</sectionName>
		<sectionItems>
			<viewName>CommissionHeaderCell</viewName>
			<data>
				<lblHeader>${Commission.status(2,全部佣金（元）)}${Commission.status(0,未结算佣金（元）)}${Commission.status(1,已结算佣金（元）)}</lblHeader>
				<lblPrice>${Commission.totalPrice}</lblPrice>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
	    <multItems>${Commission.months}</multItems>
		<sectionName>CommissionListSection</sectionName>
		<header>
			<data>
				<lblHeader>${Commission.months[0].month}</lblHeader>
			</data>
		</header>
		<sectionItems>
            <multItems>${Commission.months[0].commissionInfoList}</multItems>
            <viewName>CommissionListCell</viewName>
            <data>
                <lblDate>${Commission.months[0].commissionInfoList[0].Date}</lblDate>
                <lblPrice>${Commission.months[0].commissionInfoList[0].price}</lblPrice>
                <lblOrderNumber>${Commission.months[0].commissionInfoList[0].orderSn}</lblOrderNumber>
                <lblOrderAmount>${Commission.months[0].commissionInfoList[0].orderAmount}</lblOrderAmount>
                <lblSettleDate>${Commission.months[0].commissionInfoList[0].settleDate}</lblSettleDate>
                <lblSettled>${Commission.months[0].commissionInfoList[0].status(已结算,已结算)}</lblSettled>
                <lblSettling>${Commission.months[0].commissionInfoList[0].status(未结算,未结算)}</lblSettling>
            </data>
            <actions>
            <actionName>clickCommissonCellCommand</actionName>
                <sender>CommissionListCell</sender>
                <actionValue>${Commission.months[0].commissionInfoList[0].commissionId}</actionValue>
            </actions>
            <actions/>
        </sectionItems>
        <sectionItems/>
    </sections>
</meiQiReferrer>
