=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/payWay/payWay.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
    <xs:include schemaLocation=""></xs:include>
    <xs:element name="meiQiReferrer">    		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sections" maxOccurs="unbounded"
					minOccurs="1" type="Section" />
			</xs:sequence>
		</xs:complexType>
    </xs:element>

    <!-- 结构模板 -->
    <xs:complexType name="Section">
    	<xs:sequence>
    				<xs:element name="sectionName">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="PayWaySection">
    							</xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="sectionItems" type="SectionItem" maxOccurs="unbounded" minOccurs="1"></xs:element>
    			</xs:sequence>
    </xs:complexType>

    <xs:complexType name="SectionItem">
    	<xs:sequence>
    				<xs:element name="modelName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="PayWayCellData">
    								</xs:enumeration>
    							<xs:enumeration
    								value="PayWayOrderInfoCellData">
    							</xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="viewName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="PayWayCell">
    							</xs:enumeration>
    							 <xs:enumeration
    								value="PayWayOrderInfoCell">
    							</xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
    				<xs:element name="actions"  minOccurs="0"  maxOccurs="unbounded" type="Action"/>  <!--事件 -->
		</xs:sequence>
    </xs:complexType>
    
    
<xs:complexType name="Action">
		<xs:sequence>
			<xs:element name="actionName" minOccurs="0"> <!--事件 -->			
				<xs:simpleType> <!--数据模型名 -->
					<xs:restriction base="xs:string">			
					<xs:enumeration value="alipayCommand"></xs:enumeration> 
					<xs:enumeration value="billpayCommand"></xs:enumeration> 
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="sender" minOccurs="0" type="xs:string">
    		</xs:element>
			<xs:element name="title" minOccurs="0" type="xs:string"/> <!--按钮的标题-->
			<xs:element name="actionValue" minOccurs="0" /> <!--参数内容 -->
		</xs:sequence>
	</xs:complexType>

<!-- Data定义 -->
<xs:complexType name="PayWayCellData">
    <xs:sequence>
        <xs:element name="lblTitle" type="xs:string">
        </xs:element>
        <xs:element name="lblDescribe" type="xs:string">
        </xs:element>
        <xs:element name="imgLogo" type="xs:string">
        </xs:element>
    </xs:sequence>    
</xs:complexType>

<xs:complexType name="PayWayOrderInfoCellData">
    <xs:sequence>
        <xs:element name="lblOrderNumber" type="xs:string">
        </xs:element>
        <xs:element name="lblOrderPrice" type="xs:string">
        </xs:element>
    </xs:sequence>    
</xs:complexType>

</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/payWay/payWay_android.xml
<?xml version="1.0" encoding="UTF-8" ?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="payWay.xsd">
	<sections>
		<sectionName>PayWaySection</sectionName>
		<sectionItems>
			<modelName>PayWayOrderInfoCellData</modelName>
			<viewName>PayWayOrderInfoCell</viewName>
			<data>
				<lblOrderNumber>${OrderItem.orderSn}</lblOrderNumber>
				<lblOrderPrice>￥${OrderItem.amount}</lblOrderPrice>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>PayWaySection</sectionName>
		<sectionItems>
			<viewName>PayWayCell</viewName>
			<data>
				<lblTitle>支付宝</lblTitle>
				<lblDescribe>需安装支付宝客户端</lblDescribe>
				<imgLogo>http://image.youjiagou.com/images/s-20150616/64//812845c534047716b679dfe6cfc76854.png</imgLogo>
			</data>
			<actions>
				<actionName>alipayCommand</actionName>
		        <sender></sender>
				<title></title>
				<actionValue>
			${OrderItem.carts[0].goods[0].name} ${OrderItem.goodsAmount(1,,等多件)}|${OrderItem.orderSn}|${OrderItem.orderId}|${OrderItem.alipayNotifyURL}|${OrderItem.amount}
				</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>PayWaySection</sectionName>
		<sectionItems>
			<viewName>PayWayCell</viewName>
			<data>
				<lblTitle>微信</lblTitle>
				<lblDescribe>需安装微信客户端</lblDescribe>
				<imgLogo>http://image.youjiagou.com/images/weixin.jpg</imgLogo>
			</data>
			<actions>
				<actionName>wechatpayCommand</actionName>
		        <sender></sender>
				<title></title>
				<actionValue>
			${OrderItem.carts[0].goods[0].name} ${OrderItem.goodsAmount(1,,等多件)}|${OrderItem.orderSn}|${OrderItem.orderId}|${OrderItem.wechatNotifyURL}|${OrderItem.amount}|${OrderItem.wechatPayJson}
				</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
	    <sectionName>PayWaySection</sectionName>
	    <sectionItems>
			<viewName>PayWayCell</viewName>
			<data>
				<lblTitle>快刷</lblTitle>
				<lblDescribe>需安装快刷客户端</lblDescribe>
				<imgLogo>http://image.youjiagou.com/images/s-20150929/98/kuaishua.png</imgLogo>
			</data>
			<actions>
				<actionName>kSSwipePayCommand</actionName>
		        <sender></sender>
				<title></title>
				<actionValue>
			${OrderItem.carts[0].goods[0].name} ${OrderItem.goodsAmount(1,,等多件)}|${OrderItem.orderSn}|${OrderItem.orderId}|${OrderItem.alipayNotifyURL}|${OrderItem.amount}
				</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
   </sections>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/payWay/payWay_iphone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="payWay.xsd">
	<sections>
		<sectionName>PayWaySection</sectionName>
		<sectionItems>
			<modelName>PayWayOrderInfoCellData</modelName>
			<viewName>PayWayOrderInfoCell</viewName>
			<data>
				<lblOrderNumber>${OrderItem.orderSn}</lblOrderNumber>
				<lblOrderPrice>￥${OrderItem.amount}</lblOrderPrice>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>PayWaySection</sectionName>
		<sectionItems>
			<viewName>PayWayCell</viewName>
			<data>
				<lblTitle>支付宝</lblTitle>
				<lblDescribe>需安装支付宝客户端</lblDescribe>
				<imgLogo>http://image.lejj.com/images/s-20150616/64//812845c534047716b679dfe6cfc76854.png</imgLogo>
			</data>
			<actions>
				<actionName>alipayCommand</actionName>
		        <sender></sender>
				<title></title>
				<actionValue>
			${OrderItem.carts[0].goods[0].name} ${OrderItem.goodsAmount(1,,等多件)}|${OrderItem.orderSn}|${OrderItem.orderId}|${OrderItem.alipayNotifyURL}|${OrderItem.amount}
				</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
</meiQiReferrer>
