=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/mallHome/mallHome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
	<xs:include schemaLocation=""></xs:include>
	<xs:element name="meiQiReferrer">           
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sections" maxOccurs="unbounded"
                    minOccurs="1" type="Section" />
                <xs:element name="tools" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- 结构模板 -->

    <xs:complexType name="Section">
                <xs:sequence>
                    <xs:element name="sectionName">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration
                                    value="MallSectionForHeaderImages">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForCategory">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForMixAdvertisement">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForBannerAdvertisement">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForGoods">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForSpecialAdvertisement">
                                </xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="sectionItems" type="SectionItem" maxOccurs="unbounded" minOccurs="1"></xs:element>
                </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SectionItem">
                <xs:sequence>               
                    <xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
                    <xs:element name="viewName" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration
                                    value="MallSectionForHeaderImagesCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForCategoryCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForMixAdvertisementCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForBannerAdvertisementCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="MallSectionForSpecialAdvertisementCell">
                                </xs:enumeration>
                                <xs:enumeration
                                    value="GoodsCollectionCell">
                                </xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
                    <xs:element name="actions" type="Action" maxOccurs="unbounded" minOccurs="0"></xs:element>
                </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Action">
        <xs:sequence>
            <xs:element name="actionName" minOccurs="0">
            </xs:element>
            <xs:element name="sender" minOccurs="0">
            </xs:element>
            <xs:element name="title" minOccurs="0">
            </xs:element>
            <xs:element name="actionValue" minOccurs="0">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/mallHome/mallHome_android.xml
<meiQiReferrer   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mallHome.xsd">
    <sections>
        <sectionName>MallSectionForHeaderImages</sectionName>
        <sectionItems>
            <viewName>MallSectionForHeaderImagesCell</viewName>
        </sectionItems>
        <sectionItems/>
    </sections>
    <sections>
        <sectionName>MallSectionForCategory</sectionName>
        <sectionItems>
            <viewName>MallSectionForCategoryCell</viewName>
        </sectionItems>
        <sectionItems/>
    </sections>
    <sections>
        <sectionName>MallSectionForMixAdvertisement</sectionName>
        <sectionItems>
            <viewName>MallSectionForMixAdvertisementCell</viewName>
        </sectionItems>
        <sectionItems/>
    </sections>
    <sections>
        <sectionName>MallSectionForBannerAdvertisement</sectionName>
        <sectionItems>
            <viewName>MallSectionForBannerAdvertisementCell</viewName>
        </sectionItems>
        <sectionItems/>
    </sections>
    <sections>
        <sectionName>MallSectionForGoods</sectionName>
        <sectionItems>
            <viewName>GoodsCollectionCell</viewName>
        </sectionItems>
        <sectionItems/>
    </sections>
</meiQiReferrer>
