=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/orderDetail/orderDetail.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
    <xs:element name="meiQiReferrer">    		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sections" maxOccurs="unbounded"
					minOccurs="1" type="Section" />
				<xs:element name="tools" type="SectionItem" maxOccurs="unbounded" minOccurs="0"></xs:element>
			</xs:sequence>
		</xs:complexType>
    </xs:element>

<!-- 结构模板 -->

    <xs:complexType name="Section">
    			<xs:sequence>		
    				<xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
    				<xs:element name="sectionName">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="OrderDetailSection">
    							</xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="sectionItems" type="SectionItem" maxOccurs="unbounded" minOccurs="1"></xs:element>
    			</xs:sequence>
    </xs:complexType>

	<xs:complexType name="SectionItem">
    			<xs:sequence>    			
    				<xs:element name="multItems" type="xs:string" minOccurs="0"></xs:element>
    				<xs:element name="viewName" minOccurs="0">
    					<xs:simpleType>
    						<xs:restriction base="xs:string">
    							<xs:enumeration
    								value="OrderDetailTitleCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailConsigneeCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailCartCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailRecordCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailPriceCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailTotalCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailTransportCodeCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailTipsCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailPayCell">
    							</xs:enumeration>
    							<xs:enumeration
    								value="OrderDetailTransportInfoCell">
    							</xs:enumeration>
    							<xs:enumeration value="OrderDetailFooterToolView"></xs:enumeration>
    						</xs:restriction>
    					</xs:simpleType>
    				</xs:element>
    				<xs:element name="data" minOccurs="0" type="xs:anyType"></xs:element>
    				<xs:element name="actions" type="Action" maxOccurs="unbounded" minOccurs="0"></xs:element>
    			</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Action">
    	<xs:sequence>
    		<xs:element name="actionName" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="goodDetailCommand"></xs:enumeration> <!-- 商品详情 -->
    					<xs:enumeration value="payCommand"></xs:enumeration> <!-- 去支付 -->
    					<xs:enumeration value="cancelOrderCommand"></xs:enumeration> <!-- 取消定单 -->
    					<xs:enumeration value="confirmShipCommand"></xs:enumeration> <!-- 确认收货 -->
    					<xs:enumeration value="buyAgainCommand"></xs:enumeration> <!-- 再次购物 或者 重新购买 -->
    					<xs:enumeration value="deleteOrderCommand"></xs:enumeration> <!-- 删除定单 -->
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="sender" minOccurs="0">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="btnBlack1"></xs:enumeration>
    					<xs:enumeration value="btnBlack2"></xs:enumeration>
    					<xs:enumeration value="btnBlack3"></xs:enumeration>
    					<xs:enumeration value="btnRed"></xs:enumeration>
    					<xs:enumeration value="OrderDetailCartCell"></xs:enumeration>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="title" type="xs:string" minOccurs="0"/>
    		<xs:element name="actionValue"  minOccurs="0"/>
    	</xs:sequence>
    </xs:complexType>

<!-- Data定义 -->

	<!-- 订单状态栏 -->
	<xs:complexType name="OrderDetailTitleCell">
    	<xs:sequence>
    		<xs:element name="lblLeft" type="xs:string"></xs:element> <!-- 订单状态标签 -->
    		<xs:element name="lblLeftValue" type="xs:string"></xs:element> <!-- 订单状态 -->
    		<xs:element name="lblLeftGreenValue" type="xs:string"></xs:element> <!-- 绿色订单状态 --> 
    		<xs:element name="lblLeftValueColor" type="xs:string"></xs:element> <!-- 订单状态颜色 --> 		
    	</xs:sequence>
    </xs:complexType>


	<!-- 订单收货人Cell -->
    <xs:complexType name="OrderDetailConsigneeCell">
    	<xs:sequence>
    		<xs:element name="lblLeft" type="xs:string"></xs:element>
    		<xs:element name="lblName" type="xs:string"></xs:element>
    		<xs:element name="lblPhone" type="xs:string"></xs:element>
    		<xs:element name="lblAddress" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

	<!-- 订单商品Cell -->
    <xs:complexType name="OrderDetailCartCell">
    	<xs:sequence>
    		<xs:element name="imgvLeft" type="xs:string"></xs:element>
    		<xs:element name="lblTitle" type="xs:string"></xs:element>
    		<xs:element name="lblPrice" type="xs:string"></xs:element>
    		<xs:element name="lblGoodsAmount" type="xs:string"></xs:element>
			<xs:element name="lblStandardName" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

	<!-- 订单记录描述，订单号，下单时间 -->
    <xs:complexType name="OrderDetailRecordCell">
    	<xs:sequence>
    		<xs:element name="lblLeftTop" type="xs:string"></xs:element>
    		<xs:element name="lblRightTop" type="xs:string"></xs:element>
    		<xs:element name="lblLeftBottom" type="xs:string"></xs:element>
    		<xs:element name="lblRightBottom" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

	<!-- 订单价格描述Cell -->
    <xs:complexType name="OrderDetailPriceCell">
    	<xs:sequence>
    		<xs:element name="lblGoodsPriceLabel" type="xs:string"></xs:element> <!-- 商品价格标签 -->
    		<xs:element name="lblgoodsPrice" type="xs:string"></xs:element> <!-- 商品价格 -->
    		<xs:element name="lblTransportPriceLabel" type="xs:string"></xs:element> <!-- 运费标签 -->
    		<xs:element name="lblTransportPrice" type="xs:string"></xs:element> <!-- 运费 -->
    		<xs:element name="lblDiscountPriceLabel" type="xs:string"></xs:element> <!-- 折扣标签 -->
    		<xs:element name="lblDiscountPrice" type="xs:string"></xs:element> <!-- 折扣金额 -->
    	</xs:sequence>
    </xs:complexType>

	<!-- 实付款Cell -->
    <xs:complexType name="OrderDetailTotalCell">
    	<xs:sequence>
    		<xs:element name="lblAmountLabel" type="xs:string"></xs:element> <!-- 实付款标签 -->
    		<xs:element name="lblAmount" type="xs:string"></xs:element> <!-- 订单价格，实付款 -->
    	</xs:sequence>
    </xs:complexType>
    
    <!-- 订单号cell -->
    <xs:complexType name="OrderDetailTransportCodeCell">
    	<xs:sequence>
    		<xs:element name="lblTransportCode" type="xs:string"></xs:element> <!-- 配送单号 -->
    		<xs:element name="lblRedStatus" type="xs:string"></xs:element> <!-- 红色的配送状态 --> 
    		<xs:element name="lblGreenStatus" type="xs:string"></xs:element>  <!-- 绿色的配送状态 -->
    	</xs:sequence>
    </xs:complexType> 
    
    <!-- 提示界面 -->
    <xs:complexType name="OrderDetailTipsCell">
    	<xs:sequence>
    		<xs:element name="lblTips" type="xs:string"></xs:element> <!-- 提示语 -->
    	</xs:sequence>
    </xs:complexType>
    
    <!-- 支付方式Cell -->
    <xs:complexType name="OrderDetailPayCell">
    	<xs:sequence>
    		<xs:element name="lblPaymentsLabel" type="xs:string"></xs:element> <!-- 支付方式标签 -->
    		<xs:element name="lblPayments" type="xs:string"></xs:element> <!-- 支付方式 -->
    	</xs:sequence>
    </xs:complexType>    
    
    <!-- 配送信息Cell -->
    <xs:complexType name="OrderDetailTransportInfoCell">
    	<xs:sequence>
    		<xs:element name="lblTransportTypeLabel" type="xs:string"></xs:element> <!-- 配送信息标签 -->
    		<xs:element name="lblTransportType" type="xs:string"></xs:element> <!-- 配送信息 方式 -->
    	</xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/orderDetail/orderDetail_shipping_iphone.xml
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="orderDetail.xsd">
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTipsCell</viewName>
			<data>
				<lblTips>
					${OrderItem.allDeliveryStatus(0,您的订单正在配送中，请注意查收。,)}${OrderItem.allDeliveryStatus(1,由于订单中商品所在库房不同，部分商品已先行发货，未发货商品也将尽快发货。,)}${OrderItem.allDeliveryStatus(2,由于订单中商品所在库房不同，此订单被分拆为,)}${OrderItem.allDeliveryStatus(2,OrderItem.deliverySize,)}${OrderItem.allDeliveryStatus(2,个配送单分开配送，请您谅解。,)}
				</lblTips>
			</data>
		</sectionItems>
		<sectionItems />
	</sections>
	<sections>
		<multItems>${OrderItem.deliverys}</multItems>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTransportCodeCell</viewName>
			<data>
				<lblTransportCode>${OrderItem.deliverys[0].status(3,待发货商品)}${OrderItem.deliverys[0].status([012],配送单号：)}${OrderItem.deliverys[0].deliverySn}</lblTransportCode>
				<lblRedStatus>${OrderItem.deliverys[0].status(0,配送中)}${OrderItem.deliverys[0].status(2,生成发货单)}</lblRedStatus>
				<lblGreenStatus>${OrderItem.deliverys[0].status(1,配送完成)}</lblGreenStatus>
			</data>
		</sectionItems>
		<sectionItems>
			<multItems>${OrderItem.deliverys[0].carts}</multItems>
			<viewName>OrderDetailCartCell</viewName>
			<data>
				<imgvLeft>${OrderItem.deliverys[0].carts[0].goods.cover}</imgvLeft>
				<lblTitle>${OrderItem.deliverys[0].carts[0].goods.name}</lblTitle>
				<lblPrice>￥${OrderItem.deliverys[0].carts[0].goods.price}</lblPrice>
				<lblGoodsAmount>x${OrderItem.deliverys[0].carts[0].goodsAmount}</lblGoodsAmount>
				<lblStandardName>${OrderItem.deliverys[0].carts[0].goods.standardName}
				</lblStandardName>
			</data>
				<actions>
				<actionName>goodDetailCommand</actionName>
				<sender>OrderDetailCartCell</sender>
				<actionValue>${OrderItem.deliverys[0].carts[0].goods.goodsId}</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems />
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailConsigneeCell</viewName>
			<data>
				<lblLeft>收货人</lblLeft>
				<lblName>${OrderItem.consignee.name}</lblName>
				<lblPhone>${OrderItem.consignee.phone((\d{3})(\d{4})(\d{4}),$1****$3)}</lblPhone>
				<lblAddress>${OrderItem.consignee.detail}</lblAddress>
			</data>
		</sectionItems>
		<sectionItems />
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailPayCell</viewName>
			<data>
				<lblPaymentsLabel>支付方式</lblPaymentsLabel>
				<lblPayments>在线支付</lblPayments>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailTransportInfoCell</viewName>
			<data>
				<lblTransportTypeLabel>配送方式</lblTransportTypeLabel>
				<lblTransportType>${OrderItem.shippingStr}</lblTransportType>
			</data>
		</sectionItems>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailRecordCell</viewName>
			<data>
				<lblLeftTop>订单编号：</lblLeftTop>
				<lblRightTop>${OrderItem.orderSn}</lblRightTop>
				<lblLeftBottom>下单时间：</lblLeftBottom>
				<lblRightBottom>${OrderItem.addTime}</lblRightBottom>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailPriceCell</viewName>
			<data>
				<lblGoodsPriceLabel>商品总额</lblGoodsPriceLabel>
                <lblgoodsPrice>￥${OrderItem.goodsPrice}</lblgoodsPrice>
                <lblTransportPriceLabel>运费</lblTransportPriceLabel>
                <lblTransportPrice>+￥${OrderItem.transportPrice}</lblTransportPrice>
                <lblDiscountPriceLabel>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,折扣码优惠)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n红包优惠)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n活动优惠)}
                </lblDiscountPriceLabel>
                <lblDiscountPrice>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,-￥$0,)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n-￥$0,)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n-￥$0,)}
                </lblDiscountPrice>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailTotalCell</viewName>
			<data>
				<lblAmountLabel>实付款</lblAmountLabel>
				<lblAmount>￥${OrderItem.amount}</lblAmount>
			</data>
		</sectionItems>
	</sections>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/orderDetail/orderDetail_shippingSucceed_android.xml
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orderDetail.xsd">
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTitleCell</viewName>
			<data>
				<lblLeft>订单状态</lblLeft>			
				<lblLeftGreenValue>配送完成</lblLeftGreenValue>	
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
		<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTransportCodeCell</viewName>
			<data>
				<lblTransportCode>配送单号：${OrderItem.deliverys[0].deliverySn}</lblTransportCode>
				<lblRedStatus></lblRedStatus>
				<lblGreenStatus>配送完成</lblGreenStatus>
			</data>
		</sectionItems>
		<sectionItems>
			<multItems>${OrderItem.carts}</multItems>
			<viewName>OrderDetailCartCell</viewName>
			<data>
				<imgvLeft>${OrderItem.carts[0].goods.cover}</imgvLeft>
				<lblTitle>${OrderItem.carts[0].goods.name}</lblTitle>
				<lblPrice>￥${OrderItem.carts[0].goods.price}</lblPrice>
				<lblGoodsAmount>x${OrderItem.carts[0].goodsAmount}</lblGoodsAmount>
				<lblStandardName>${OrderItem.carts[0].goods.standardName}
				</lblStandardName>
				<lblGoodId>${OrderItem.carts[0].goods.goodsId}</lblGoodId>
			</data>
				<actions>
				<actionName>goodDetailCommand</actionName>
				<sender>OrderDetailCartCell</sender>
				<actionValue>${OrderItem.carts[0].goods.goodsId}</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailConsigneeCell</viewName>
			<data>
				<lblLeft>收货人</lblLeft>
				<lblName>${OrderItem.consignee.name}</lblName>
				<lblPhone>${OrderItem.consignee.phone((\d{3})(\d{4})(\d{4}),$1****$3)}</lblPhone>
				<lblAddress>${OrderItem.consignee.detail}</lblAddress>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>	
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailPayCell</viewName>
			<data>
				<lblPaymentsLabel>支付方式</lblPaymentsLabel>
				<lblPayments>在线支付</lblPayments>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailTransportInfoCell</viewName>
			<data>
				<lblTransportTypeLabel>配送信息</lblTransportTypeLabel>
				<lblTransportType>普通快递</lblTransportType>
			</data>
		</sectionItems>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailRecordCell</viewName>
			<data>
				<lblLeftTop>订单编号：</lblLeftTop>
				<lblRightTop>${OrderItem.orderSn}</lblRightTop>
				<lblLeftBottom>下单时间：</lblLeftBottom>
				<lblRightBottom>${OrderItem.addTime}</lblRightBottom>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailPriceCell</viewName>
			<data>
			    <lblGoodsPriceLabel>商品总额</lblGoodsPriceLabel>
                <lblgoodsPrice>￥${OrderItem.goodsPrice}</lblgoodsPrice>
                <lblTransportPriceLabel>运费</lblTransportPriceLabel>
                <lblTransportPrice>+￥${OrderItem.transportPrice}</lblTransportPrice>
                <lblDiscountPriceLabel>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,折扣码优惠)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n红包优惠)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n活动优惠)}
                </lblDiscountPriceLabel>
                <lblDiscountPrice>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,-￥$0,)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n-￥$0,)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\n-￥$0,)}
                </lblDiscountPrice>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailTotalCell</viewName>
			<data>
				<lblAmountLabel>实付款</lblAmountLabel>
				<lblAmount>￥${OrderItem.amount}</lblAmount>
			</data>
		</sectionItems>
	</sections>
	<tools>
		<viewName>OrderDetailFooterToolView</viewName>
		<actions>
		<actionName>confirmShipCommand</actionName>
			<sender>btnRed</sender>
			<title>确认收货</title>
			<actionValue>${OrderItem.orderId}</actionValue>
		</actions>
		<actions/>
	</tools>
    <tools/>
</meiQiReferrer>

=== OlaYang/DSORM/src/main/resources/lejj_resource/xml/orderDetail/orderDetail_waitPay_iphone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<meiQiReferrer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orderDetail.xsd">
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTitleCell</viewName>
			<data>
				<lblLeft>订单状态</lblLeft>			
				<lblLeftValue>等待付款</lblLeftValue>	
				<lblLeftValueColor>990000</lblLeftValueColor>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailConsigneeCell</viewName>
			<data>
				<lblLeft>收货人</lblLeft>
				<lblName>${OrderItem.consignee.name}</lblName>
				<lblPhone>${OrderItem.consignee.phone((\d{3})(\d{4})(\d{4}),$1****$3)}</lblPhone>
				<lblAddress>${OrderItem.consignee.detail}</lblAddress>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>	
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<multItems>${OrderItem.carts}</multItems>
			<viewName>OrderDetailCartCell</viewName>
			<data>
				<imgvLeft>${OrderItem.carts[0].goods.cover}</imgvLeft>
				<lblTitle>${OrderItem.carts[0].goods.name}</lblTitle>
				<lblPrice>￥${OrderItem.carts[0].goods.price}</lblPrice>
				<lblGoodsAmount>x${OrderItem.carts[0].goodsAmount}</lblGoodsAmount>
				<lblStandardName>${OrderItem.carts[0].goods.standardName}
				</lblStandardName>
				<lblGoodId>${OrderItem.carts[0].goods.goodsId}</lblGoodId>
			</data>
			<actions>
				<actionName>goodDetailCommand</actionName>
				<sender>OrderDetailCartCell</sender>
				<actionValue>${OrderItem.carts[0].goods.goodsId}</actionValue>
			</actions>
			<actions/>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailTransportInfoCell</viewName>
			<data>
				<lblTransportTypeLabel>配送方式</lblTransportTypeLabel>
				<lblTransportType>${OrderItem.shippingStr}</lblTransportType>
			</data>
		</sectionItems>
		<sectionItems/>
	</sections>
	<sections>
		<sectionName>OrderDetailSection</sectionName>
		<sectionItems>
			<viewName>OrderDetailRecordCell</viewName>
			<data>
				<lblLeftTop>订单编号：</lblLeftTop>
				<lblRightTop>${OrderItem.orderSn}</lblRightTop>
				<lblLeftBottom>下单时间：</lblLeftBottom>
				<lblRightBottom>${OrderItem.addTime}</lblRightBottom>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailPriceCell</viewName>
			<data>
				<lblGoodsPriceLabel>商品总额</lblGoodsPriceLabel>
                <lblgoodsPrice>￥${OrderItem.goodsPrice}</lblgoodsPrice>
                <lblTransportPriceLabel>运费</lblTransportPriceLabel>
                <lblTransportPrice>+￥${OrderItem.transportPrice}</lblTransportPrice>
                <lblDiscountPriceLabel>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,折扣码优惠)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\\n红包优惠)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\\n活动优惠)}
                </lblDiscountPriceLabel>
                <lblDiscountPrice>
                ${OrderItem.orderDiscount.discount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,-￥$0,)}${OrderItem.orderDiscount.bonusDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\\n-￥$0,)}${OrderItem.orderDiscount.orderDiscount((?!0+(?:\.0+)?$)\d+(?:\.\d+)?,\\n-￥$0,)}
                </lblDiscountPrice>
			</data>
		</sectionItems>
		<sectionItems>
			<viewName>OrderDetailTotalCell</viewName>
			<data>
				<lblAmountLabel>实付款</lblAmountLabel>
				<lblAmount>￥${OrderItem.amount}</lblAmount>
			</data>
		</sectionItems>
	</sections>
	<tools>
		<viewName>OrderDetailFooterToolView</viewName>
		<actions>
			<actionName>cancelOrderCommand</actionName>
			<sender>btnBlack2</sender>
			<title>取消订单</title>
			<actionValue>${OrderItem.orderId}</actionValue>
		</actions>
		<actions>
		<actionName>payCommand</actionName>
			<sender>btnRed</sender>
			<title>去支付</title>
			<actionValue>${OrderItem.orderId}</actionValue>
		</actions>
	</tools>
    <tools/>
</meiQiReferrer>
